### ISSUE TITLE
好像 ESlint 的配置有点问题

### ISSUE THREAD

**Issue by youmikuang** [isolcat/vue3-ts-bilibili#1]
不能自动格式化，是我配置有问题还是使用姿势有问题，求指教~

**Comment by isolcat** [comment]
eslint配置有些复杂，我在开发过程中也遇见了很多问题，踩了很多坑，所以我将自动格式化给取消了，避免了一些报错，你可以自己修改eslint配置来开启，你可以参考[这篇文章](https://www.iszy.cc/posts/12/)，希望能够帮到你

**Comment by youmikuang** [comment]
> 

好的 那我看下吧，我觉得这块确实不容易。谢谢
